version: '3.7'

services:

        web:
                build: 
                        context: ./web
                        dockerfile: Dockerfile

        db:
                build: 
                        context: ./db/
                        dockerfile: Dockerfile

